<?php
return array (
  'permission_interface.bookmarkPermissions' => 'Bookmark permissions',
  'permission_interface.conversationModeratorPermissions' => 'Conversation moderator permissions',
  'permission_interface.conversationPermissions' => 'Conversation permissions',
  'permission_interface.forumModeratorPermissions' => 'Forum moderator permissions',
  'permission_interface.forumPermissions' => 'Forum permissions',
  'permission_interface.generalModeratorPermissions' => 'General moderator permissions',
  'permission_interface.generalPermissions' => 'General permissions',
  'permission_interface.postAttachmentPermissions' => 'Post attachment permissions',
  'permission_interface.profilePostModeratorPermissions' => 'Profile post moderator permissions',
  'permission_interface.profilePostPermissions' => 'Profile post permissions',
  'permission_interface.signaturePermissions' => 'Signature permissions',
  'permission_interface.th_uix' => 'UI.X Permissions',
  'permission_interface.xa_amsArticle' => 'Article Management System: Article permissions',
  'permission_interface.xa_amsArticleModerator' => 'Article Management System: Article moderator permissions',
  'permission_interface.xa_amsComment' => 'Article Management System: Comment permissions',
  'permission_interface.xa_amsCommentModerator' => 'Article Management System: Comment moderator permissions',
  'permission_interface.xa_amsRating' => 'Article Management System: Rate/Review permissions',
  'permission_interface.xa_amsRatingModerator' => 'Article Management System: Rate/Review moderator permissions',
  'permission_interface.xa_amsSeries' => 'Article Management System: Series permissions',
  'permission_interface.xa_amsSeriesModerator' => 'Article Management System: Series moderator permissions',
);