<?php
return array (
  'nav._default' => 'Mặc định (không chọn)',
  'nav.chay' => 'CHẠY',
  'nav.contributedThreads' => 'Chủ đề có bài viết của bạn',
  'nav.currentVisitors' => 'Thành viên trực tuyến',
  'nav.defaultLatestActivity' => 'Hoạt động mới nhất',
  'nav.defaultLogOut' => 'Đăng xuất',
  'nav.defaultNewsFeed' => 'Luồng tin của bạn',
  'nav.defaultRegister' => 'Đăng ký',
  'nav.defaultYourAccount' => 'Tài khoản của bạn',
  'nav.defaultYourProfile' => 'Hồ sơ của bạn',
  'nav.dibo' => 'ĐI BỘ',
  'nav.findThreads' => 'Tìm chủ đề',
  'nav.forumList' => 'Danh sách diễn đàn',
  'nav.forums' => 'Diễn Đàn',
  'nav.home' => 'Trang chủ',
  'nav.latestActivity' => 'Hoạt động mới nhất',
  'nav.markForumsRead' => 'Đánh dấu đã xem',
  'nav.members' => 'Thành Viên',
  'nav.newPosts' => 'Bài viết mới',
  'nav.newProfilePosts' => 'Bài mới trên hồ sơ',
  'nav.registeredMembers' => 'Đăng ký',
  'nav.searchForums' => 'Tìm chủ đề',
  'nav.searchProfilePosts' => 'Tìm trong hồ sơ cá nhân',
  'nav.unansweredThreads' => 'Chủ đề chưa trả lời',
  'nav.watched' => 'Theo dõi',
  'nav.watchedForums' => 'Diễn đàn đã theo dõi',
  'nav.watchedThreads' => 'Chủ đề đã theo dõi',
  'nav.whatsNew' => 'Tin Mới',
  'nav.whatsNewNewsFeed' => 'Luồng tin của bạn',
  'nav.whatsNewPosts' => 'Bài viết mới',
  'nav.whatsNewProfilePosts' => 'Bài mới trên hồ sơ',
  'nav.yourThreads' => 'Chủ đề của tôi',
);