<?php
return array (
  'alert_opt_out.ams_article_insert' => 'Adds a new article to a watched category',
  'alert_opt_out.ams_article_mention' => 'Mentions you in an article',
  'alert_opt_out.ams_article_reaction' => 'Reacts to your article',
  'alert_opt_out.ams_comment_insert' => 'Comments on a watched article
',
  'alert_opt_out.ams_comment_mention' => 'Mentions you in a article comment',
  'alert_opt_out.ams_comment_quote' => 'Quotes your article comment',
  'alert_opt_out.ams_comment_reaction' => 'Reacts to your article comment',
  'alert_opt_out.ams_page_insert' => 'Adds a new page to a watched article',
  'alert_opt_out.ams_page_reaction' => 'Reacts to your article page',
  'alert_opt_out.ams_rating_insert' => 'Rates your article',
  'alert_opt_out.ams_rating_mention' => 'Mentions you in a article review',
  'alert_opt_out.ams_rating_reaction' => 'Reacts to your article review',
  'alert_opt_out.ams_series_insert' => 'Adds a new series',
  'alert_opt_out.ams_series_part_insert' => 'Adds a new article to a watched series',
  'alert_opt_out.ams_series_reaction' => 'Reacts to your series',
  'alert_opt_out.conversation_message_reaction' => 'Phản ứng với tin nhắn của bạn trong cuộc trò chuyện',
  'alert_opt_out.post_forumwatch_insert' => 'Bài viết trong chuyên mục đã theo dõi',
  'alert_opt_out.post_insert' => 'Trả lời chủ đề đã theo dõi',
  'alert_opt_out.post_mention' => 'Nhắc đến bạn trong một tin nhắn',
  'alert_opt_out.post_quote' => 'Trích dẫn bài viết của bạn',
  'alert_opt_out.post_reaction' => 'Phản ứng với tin nhắn của bạn',
  'alert_opt_out.profile_post_comment_other_commenter' => 'Có bình luận về bài viết trong hồ sơ',
  'alert_opt_out.profile_post_comment_reaction' => 'Reacts to your profile post comment',
  'alert_opt_out.profile_post_comment_your_post' => 'Bình luận về hồ sơ của bạn cho các thành viên khác',
  'alert_opt_out.profile_post_comment_your_profile' => 'Bình luận về hồ sơ hoặc trạng thái của bạn',
  'alert_opt_out.profile_post_insert' => 'Đăng trên hồ sơ của bạn',
  'alert_opt_out.profile_post_mention' => 'Nhắc đến bạn trong bài viết hồ sơ hoặc bình luận',
  'alert_opt_out.profile_post_reaction' => 'Reacts to your profile post',
  'alert_opt_out.trophy_award' => 'Nhận danh hiệu mới',
  'alert_opt_out.user_following' => 'Bắt đầu theo dõi bạn',
);