<?php
return array (
  'permission_interface.bookmarkPermissions' => 'Bookmark permissions',
  'permission_interface.conversationModeratorPermissions' => 'Quyền quản lý đối thoại',
  'permission_interface.conversationPermissions' => 'Quyền đối thoại',
  'permission_interface.forumModeratorPermissions' => 'Quyền kiểm duyệt viên diễn đàn',
  'permission_interface.forumPermissions' => 'Quyền diễn đàn',
  'permission_interface.generalModeratorPermissions' => 'Quyền kiểm duyệt viên chung',
  'permission_interface.generalPermissions' => 'Quyền chung',
  'permission_interface.postAttachmentPermissions' => 'Post attachment permissions',
  'permission_interface.profilePostModeratorPermissions' => 'Quyền quản lý bài viết trên hồ sơ',
  'permission_interface.profilePostPermissions' => 'Quyền bài viết trên hồ sơ',
  'permission_interface.signaturePermissions' => 'Quyền chữ ký',
  'permission_interface.th_uix' => 'UI.X Permissions',
  'permission_interface.xa_amsArticle' => 'Article Management System: Article permissions',
  'permission_interface.xa_amsArticleModerator' => 'Article Management System: Article moderator permissions',
  'permission_interface.xa_amsComment' => 'Article Management System: Comment permissions',
  'permission_interface.xa_amsCommentModerator' => 'Article Management System: Comment moderator permissions',
  'permission_interface.xa_amsRating' => 'Article Management System: Rate/Review permissions',
  'permission_interface.xa_amsRatingModerator' => 'Article Management System: Rate/Review moderator permissions',
  'permission_interface.xa_amsSeries' => 'Article Management System: Series permissions',
  'permission_interface.xa_amsSeriesModerator' => 'Article Management System: Series moderator permissions',
);