<?php
return array (
  'widget_def.birthdays' => 'Today\'s birthdays',
  'widget_def.find_member' => 'Tìm thành viên',
  'widget_def.forum_statistics' => 'Thống kê diễn đàn',
  'widget_def.html' => 'HTML',
  'widget_def.member_stat' => 'Member stat',
  'widget_def.members_online' => 'Thành viên trực tuyến',
  'widget_def.new_posts' => 'Bài viết mới',
  'widget_def.new_profile_posts' => 'Bài viết hồ sơ mới nhất',
  'widget_def.new_threads' => 'New threads',
  'widget_def.newest_members' => 'Thành viên mới',
  'widget_def.online_statistics' => 'Thống kê trực tuyến',
  'widget_def.php_callback' => 'Hàm PHP',
  'widget_def.search_forum' => 'Search forum',
  'widget_def.share_page' => 'Chia sẻ trang',
  'widget_def.template_syntax' => 'Template syntax',
  'widget_def.th_post_thread_uix' => '[UI.X] Start a thread',
  'widget_def.th_widget_login_uix' => '[UI.X] Login form',
  'widget_def.thread_poll' => 'Thread poll',
  'widget_def.thuix_socialMedia' => '[TH] UI.X social media feed',
  'widget_def.visitor_panel' => 'Bảng khách truy cập',
  'widget_def.xa_ams_article_page_poll' => 'AMS: Article page poll',
  'widget_def.xa_ams_article_poll' => 'AMS: Article poll',
  'widget_def.xa_ams_article_statistics' => 'AMS: Articles statistics',
  'widget_def.xa_ams_articles_map' => 'AMS: Articles map',
  'widget_def.xa_ams_category_nav' => 'AMS: Category navigation',
  'widget_def.xa_ams_featured_articles' => 'AMS: Featured articles',
  'widget_def.xa_ams_featured_series' => 'AMS: Featured series',
  'widget_def.xa_ams_latest_articles' => 'AMS: Latest articles',
  'widget_def.xa_ams_latest_comments' => 'AMS: Latest comments',
  'widget_def.xa_ams_latest_reviews' => 'AMS: Latest reviews',
  'widget_def.xa_ams_latest_series' => 'AMS: Latest series',
  'widget_def.xa_ams_series_poll' => 'AMS: Series poll',
);