<?php
return array (
  'alert_opt_out.ams_article_insert' => 'Adds a new article to a watched category',
  'alert_opt_out.ams_article_mention' => 'Mentions you in an article',
  'alert_opt_out.ams_article_reaction' => 'Reacts to your article',
  'alert_opt_out.ams_comment_insert' => 'Comments on a watched article
',
  'alert_opt_out.ams_comment_mention' => 'Mentions you in a article comment',
  'alert_opt_out.ams_comment_quote' => 'Quotes your article comment',
  'alert_opt_out.ams_comment_reaction' => 'Reacts to your article comment',
  'alert_opt_out.ams_page_insert' => 'Adds a new page to a watched article',
  'alert_opt_out.ams_page_reaction' => 'Reacts to your article page',
  'alert_opt_out.ams_rating_insert' => 'Rates your article',
  'alert_opt_out.ams_rating_mention' => 'Mentions you in a article review',
  'alert_opt_out.ams_rating_reaction' => 'Reacts to your article review',
  'alert_opt_out.ams_series_insert' => 'Adds a new series',
  'alert_opt_out.ams_series_part_insert' => 'Adds a new article to a watched series',
  'alert_opt_out.ams_series_reaction' => 'Reacts to your series',
  'alert_opt_out.conversation_message_reaction' => 'Reacts to your message in a conversation',
  'alert_opt_out.post_forumwatch_insert' => 'Posts in a watched forum',
  'alert_opt_out.post_insert' => 'Replies to a watched thread',
  'alert_opt_out.post_mention' => 'Mentions you in a message',
  'alert_opt_out.post_quote' => 'Quotes your message',
  'alert_opt_out.post_reaction' => 'Reacts to your message',
  'alert_opt_out.profile_post_comment_other_commenter' => 'Also comments on a profile post',
  'alert_opt_out.profile_post_comment_reaction' => 'Reacts to your profile post comment',
  'alert_opt_out.profile_post_comment_your_post' => 'Comments on your profile posts for other members',
  'alert_opt_out.profile_post_comment_your_profile' => 'Comments on your profile or status',
  'alert_opt_out.profile_post_insert' => 'Posts on your profile',
  'alert_opt_out.profile_post_mention' => 'Mentions you in a profile post or comment',
  'alert_opt_out.profile_post_reaction' => 'Reacts to your profile post',
  'alert_opt_out.trophy_award' => 'Awards you a new trophy',
  'alert_opt_out.user_following' => 'Starts following you',
);