<?php
return array (
  'widget_def.birthdays' => 'Today\'s birthdays',
  'widget_def.find_member' => 'Find member',
  'widget_def.forum_statistics' => 'Forum statistics',
  'widget_def.html' => 'HTML',
  'widget_def.member_stat' => 'Member stat',
  'widget_def.members_online' => 'Members online',
  'widget_def.new_posts' => 'New posts',
  'widget_def.new_profile_posts' => 'New profile posts',
  'widget_def.new_threads' => 'New threads',
  'widget_def.newest_members' => 'Newest members',
  'widget_def.online_statistics' => 'Online statistics',
  'widget_def.php_callback' => 'PHP callback',
  'widget_def.search_forum' => 'Search forum',
  'widget_def.share_page' => 'Share this page',
  'widget_def.template_syntax' => 'Template syntax',
  'widget_def.th_post_thread_uix' => '[UI.X] Start a thread',
  'widget_def.th_widget_login_uix' => '[UI.X] Login form',
  'widget_def.thread_poll' => 'Thread poll',
  'widget_def.thuix_socialMedia' => '[TH] UI.X social media feed',
  'widget_def.visitor_panel' => 'Visitor panel',
  'widget_def.xa_ams_article_page_poll' => 'AMS: Article page poll',
  'widget_def.xa_ams_article_poll' => 'AMS: Article poll',
  'widget_def.xa_ams_article_statistics' => 'AMS: Articles statistics',
  'widget_def.xa_ams_articles_map' => 'AMS: Articles map',
  'widget_def.xa_ams_category_nav' => 'AMS: Category navigation',
  'widget_def.xa_ams_featured_articles' => 'AMS: Featured articles',
  'widget_def.xa_ams_featured_series' => 'AMS: Featured series',
  'widget_def.xa_ams_latest_articles' => 'AMS: Latest articles',
  'widget_def.xa_ams_latest_comments' => 'AMS: Latest comments',
  'widget_def.xa_ams_latest_reviews' => 'AMS: Latest reviews',
  'widget_def.xa_ams_latest_series' => 'AMS: Latest series',
  'widget_def.xa_ams_series_poll' => 'AMS: Series poll',
);